- name: Install Base Packages
  become: yes
  ansible.builtin.package:
    name:
      - wget
      - net-tools
      - vim
      - git
      - curl
      - gcc
      - make
      - traceroute
      - automake
      - autoconf

- name: Install Chrome
  become: yes
  apt:
    deb: 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb'