- name: Install Base Packages
  become: yes
  ansible.builtin.package:
    name:
      - wget
      - net-tools
      - vim
      - git
      - curl
      - gcc
      - make
      - traceroute
      - automake
      - autoconf
      - python3-pip
      - python3-venv
